# Generated by Django 5.1.1 on 2024-09-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoLoginApp', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='noemail@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.TextField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
