# Generated by Django 5.1.1 on 2024-09-26 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoLoginApp', '0004_alter_user_email_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
